apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: obo-web
  name: obo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obo-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: obo-web
    spec:
      containers:
      - image: minnthaii/obo-web:1.7
        name: obo-web
        envFrom:
        - configMapRef:
            name: obo-web-configmap
        resources: {}
status: {}
