apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: static-web2
  name: static-web2
spec:
  ports:
  - name: 8081-80
    port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: static-web2
  type: NodePort
status:
  loadBalancer: {}
